# frozen_string_literal: true

source "https://rubygems.org"

gem "rails"
# gem "aws-sdk-s3"
gem "ox"
gem "jwt"
gem 'aws-sdk-s3', '1.123.1'
gem 'aws-sdk-core', '3.174.0'
gem 'aws-sdk-kms', '1.65.0'
gem 'aws-sigv4', '1.5.2'
gem 'aws-eventstream', '1.2.0'
gem 'aws-partitions', '1.774.0'
gem 'jmespath', '1.6.2'
