#!/usr/bin/bash

docker build --build-arg REACT_APP_BACKEND_URL="http://api.fisayofasuyi.tech" --build-arg REACT_APP_AWS_PROJECT_REGION="us-east-1" --build-arg REACT_APP_AWS_COGNITO_REGION="us-east-1" --build-arg REACT_APP_AWS_USER_POOLS_ID="us-east-1_GytnSn5Lo" --build-arg REACT_APP_CLIENT_ID="1leg188bgfi4r4qmjtfo1r85g7" -t frontend-react-js -f Dockerfile.prod .